
const BASE_URL = 'https://leetcode.com'
const LEETCODE_URL = 'https://leetcode.com/problems'

const POPUP_THEME_COMMAND = 'SET_POPUP_THEME'
const LEETCODE_THEME_COMMAND = 'SET_LEETCODE_THEME'
const LEETCODE_RESET_COMMAND = 'SET_LEETCODE_AUTO_RESET'
const MONACO_THEME_COMMAND = 'SET_MONACO_THEME'
const ENABLE_MONACO_THEME_COMMAND = 'SET_ENABLE_MONACO_THEME'
const DEFAULT_MONACO_THEME_COMMAND = 'SET_DEFAULT_MONACO_THEME'

const POPUP_THEME_KEY = 'POPUP_THEME'
const LEETCODE_THEME_KEY = 'lc-dark-side'
const LEETCODE_RESET_KEY = 'LEETCODE_AUTO_RESET'
const ENABLE_MONACO_THEME_KEY = 'ENABLE_MONACO_THEME'
const MONACO_THEME_KEY = 'LEETCODE_MONACO_THEME'
const MONACO_BACKGROUND_KEY = 'LEETCODE_MONACO_THEME_BACKGROUND'
