
const BASE_URL = 'https://leetcode.com'
const LEETCODE_URL = 'https://leetcode.com/problems'

const THEME_SWITCH = 'SWITCH_MONACO_THEME'
const THEME_COMMAND = 'SET_MONACO_THEME'
const LEETCODE_THEME_COMMAND = 'SET_LEETCODE_THEME'
const DEFAULT_THEME_COMMAND = 'SET_DEFAULT_MONACO_THEME'
const THEME_LOAD = 'LOAD_MONACO_THEME'
const THEME_RESPONSE = 'SET_MONACO_THEME_RESPONSE'

const ENABLE_MONACO_THEME_KEY = 'ENABLE_MONACO_THEME'
const MONACO_THEME_KEY = 'LEETCODE_MONACO_THEME'
const MONACO_BACKGROUND_KEY = 'LEETCODE_MONACO_THEME_BACKGROUND'
const POPUP_THEME_KEY = 'POPUP_THEME'
const LEETCODE_THEME_KEY = 'lc-dark-side'

const LIGHT_THEME_EDITOR_BACKGROUND = '#ffffff'
const DARK_THEME_EDITOR_BACKGROUND = '#262626'
