
const BASE_URL = 'https://leetcode.com'
const LEETCODE_URL = 'https://leetcode.com/problems'
const THEME_SWITCH = 'SWITCH_MONACO_THEME'
const THEME_COMMAND = 'SET_MONACO_THEME'
const THEME_KEY = 'LEETCODE_MONACO_THEME'
const THEME_BACKGROUND_KEY = 'LEETCODE_MONACO_THEME_BACKGROUND'
const THEME_RESPONSE = 'SET_MONACO_THEME_RESPONSE'
